export const Legends = [
  { name: 'AED Locations', value: 'aed_locations', icon:'rocket' },
  { name: 'AXS Stations', value: 'axs_stations', icon: 'rail-metro' },
  { name: 'Child Care', value: 'child_care', icon: 'ice-cream' },
  { name: 'Community Clubs', value: 'community_clubs', icon: 'golf' },
  { name: 'Constituency Offices', value: 'constituency_offices', icon: 'information' },
  { name: 'Disability Care', value: 'disability_care', icon: 'doctor' },
  { name: 'Elder Care', value: 'elder_care', icon: 'lodging' },
  { name: 'Hawker Centres', value: 'hawker_centres', icon: 'fast-food' },
  { name: 'Historic Sites', value: 'historic_sites', icon: 'monument' },
  { name: 'Hospitals', value: 'hospitals', icon: 'hospital' },
  { name: 'Hotels', value: 'hotels', icon: 'restaurant' },
  { name: 'Kindergardens', value: 'kinder_gardens', icon: 'playground' },
  { name: 'Libraries', value: 'libraries', icon: 'library' },
  { name: 'Money Exchangers', value: 'money_xchanger', icon: 'stadium' },
  { name: 'Museums', value: 'museum', icon: 'museum' },
  { name: 'Nursing Homes', value: 'nursing_home', icon: 'garden' },
  { name: 'Pharmacies', value: 'pharmacy', icon: 'pharmacy' },
  { name: 'Pre-Schools', value: 'preschools', icon: 'zoo' },
  { name: 'Private Institutions', value: 'private_inst', icon: 'college' },
  { name: 'Remittance', value: 'remittance', icon: 'town-hall' },
  { name: 'Schools', value: 'schools', icon: 'school' },
  { name: 'Student Care', value: 'student_care', icon: 'triangle' },
  { name: 'Supermarket', value: 'super_market', icon: 'grocery' },
  { name: 'Train Stations', value: 'train_station_names', icon: 'rail-metro' },
  { name: 'Voluntary Welfare', value: 'voluntary_welfare', icon: 'star' }
];
